version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=962804699607.dkr.ecr.us-west-2.amazonaws.com/g5-capstone2-ecr
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t g5-capstone2-image:latest .
      - docker tag g5-capstone2-image:latest $REPOSITORY_URI
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      